Kristo/pdf-toc
NYPL/web-reader pull request #151
Opened 2023-02-07 00:36 UTC by kristojorg

This PR:

1. Extracts the reducer, types, and utility functions into separate files for easier understanding
2. Makes a `GO_FORWARD` `GO_BACKWARD` and `GO_TO_HREF` action.
3. Moves all action logic into the reducer (out of the callback) so it can be shared easier and centralized.
4. Makes an effect that scrolls the user to the correct page when the page number chanages. 
5. Updates `addTocToManifest` to avoid passing a mutable `toc` value to a separate function.

There is one more thing I would like to try, which is adding the toc to the manifest outside of the web reader. I will have to give this a go tomorrow

2023-02-07 16:58 UTC, jackiequach requested changes
Overall changes look great! Left a few minor comments.

Also, when switching tabs for [Single-PDF Webpub](https://web-reader-git-kristo-pdf-toc-nypl.vercel.app/pdf/single-resource-short), the PDF seems to reload and the page resets to 1. I'm unsure where this issue may have been introduced.

2023-02-07 16:58 UTC, jackiequach commented on example/index.tsx
> +  const syntheticUrl = URL.createObjectURL(
Didn't know this was possible. Very cool!

2023-02-07 16:58 UTC, jackiequach commented on src/PdfReader/addTocToManifest.tsx
> +    // await all the promises and filter any undefined values (tere was no chapter.dest or pageIndex)
typo in parenthesis

2023-02-07 16:58 UTC, jackiequach commented on src/PdfReader/reducer.ts
> +      // check if there is a #startPage in the href of the resource we are navigating to
change "#startPage" to "?startPage"

2023-02-07 16:58 UTC, jackiequach commented on src/PdfReader/reducer.ts
> +        const atStartOfResource = state.pageNumber === 1;
This will not work for multi-pdf resources since the start of the resource will be the value from ?startPage=X.

2023-02-09 11:18 UTC, kristojorg commented on src/PdfReader/reducer.ts
> +        const atStartOfResource = state.pageNumber === 1;
Very good point, I'll update this

2023-02-10 20:24 UTC, jackiequach commented on example/index.tsx
> +const fetchAndModifyManifest: Fetcher<string, string> = async (url) => {
Should this method be moved and exported for consuming apps to use, or documented as a code snippet to be added in consuming apps?

2023-02-14 15:34 UTC, kristojorg commented on example/index.tsx
> +const fetchAndModifyManifest: Fetcher<string, string> = async (url) => {
That's not a bad idea... I was thinking we could leave the fetching to the consuming app in case they have particular ways they need to do it. I will update the README however with this code snippet : )

2023-02-14 15:43 UTC, kristojorg commented
Updated the README, LMK what you think @jackiequach : )

2023-02-14 15:54 UTC, kristojorg commented
@jackiequach I am unable to get cypress to run locally to debug the failing test... There seems to be some error with my M1 mac. Maybe cypress needs to be upgraded? Are you able to get it to run?

2023-02-14 17:08 UTC, jackiequach commented
@kristojorg I am able to run the cypress tests locally. multi-pdf/navigations.ts > Scrolling mode & TOC: should update page content after clicking on TOC link is failing. This is most likely due to skipping the interstitial pages on scroll mode and changing the content visible on the page.

2023-02-15 16:00 UTC, samanthaandrews commented
@jackiequach Since things are ramping up for Kristo on PJR, I'm thinking it makes sense for you to fix these Cypress tests and get this PR ready to merge. Let me know if you think this is something you can do. You can create a ticket for it or take over a the ticket that Kristo created if it exists.

We do need to figure out the issue with the Cypress tests not running for Kristo, but I think that task will have to wait.

2023-02-18 08:45 UTC, kristojorg commented
Thanks so much @jackiequach ! Feel free to merge this whenever you're ready

2023-02-21 15:06 UTC, jackiequach approved these changes

2023-02-21 15:50 UTC, merged