[WIP] SFR-1290 single pdf toc
NYPL/web-reader pull request #68
Opened 2021-09-29 21:25 UTC by hokei

This PR injects the PDFjs Outline to the Table of Contents.  
Wanted to get some feedback on the organization of `TableOfContent.tsx` - it's now starting to look pretty messy, and I'm wondering if it's going to be easier to have a separate `PDFOutlineToc` and a `WebpubToc` but have it share the same styling.

Still outstanding: 
- [ ] The current chapter should be highlighted on PDFs. 
- [ ] Tests for TOC functionality, in Epub, Multi PDF and Single PDF instances

2021-09-29 21:27 UTC, hokei commented on .storybook/preview.jsx
> +const React = require("react")
Looks like there's stuff my linter is doing differently ... what settings are y'all using for jsx?

2021-10-03 23:49 UTC, samanthaandrews commented
> Wanted to get some feedback on the organization of TableOfContent.tsx - it's now starting to look pretty messy, and I'm wondering if it's going to be easier to have a separate PDFOutlineToc and a WebpubToc but have it share the same styling.

This is looking really good! I do think splitting up PDFOutlineToc and WebpubToc makes sense for clarity.

2021-10-04 11:53 UTC, kristojorg requested changes
I think we should try to keep the pdf-specific toc stuff out of our ui components by using the Readium `Locator` abstraction or even just url hashes: `goTo('resourceUrl#page=2')`. Let's huddle about this today if we can!

2021-10-04 11:53 UTC, kristojorg commented on package.json
> +    "example": "parcel example/index.html",
Hopefully we don't still need this? It overrides the settings at line 68 in this file

2021-10-04 11:53 UTC, kristojorg commented on src/types.ts
> +export type PdfReaderState = ReaderState & { pdf?: PDFDocumentProxy };
If I'm not wrong, this should be added inside `/PdfReader/index.tsx` in the `PdfState`. The `PdfReaderState` type here is meant to be the public-facing state that is returned by `usePdfReader`, but I don't think that consumers of `usePdfReader` would want access to that? The `PdfState` is where I keep state that is internal to the component. Confusing, I know. I should do rename these things

2021-10-04 11:53 UTC, kristojorg commented on src/PdfReader/index.tsx
> +    (target: string | any[]) => {
This works for now, but I think in the future we should try to make this work with a Readium `Locator` object, which I believe is supposed to handle cases where it is a page or specific location within a resource. Thus we can avoid having the react-pdf specific logic and types leak out of `usePdfReader`

2021-10-04 11:53 UTC, kristojorg commented on src/PdfReader/index.tsx
> +    (target: string | any[]) => {
[Here is locator reference](https://readium.org/architecture/models/locators/)

2021-10-04 11:53 UTC, kristojorg commented on src/PdfReader/index.tsx
> +    (target: string | any[]) => {
This is what a pdf locator would look like:
```
{
  "href": "http://example.com/document",
  "type": "application/pdf",
  "title": "Page 5",
  "locations": {
    "fragments": ["page=5", "viewrect=50,50,640,480"],
    "progression": 0.12703,
    "totalProgression": 0.12703
  }
}
```

2021-10-04 11:53 UTC, kristojorg commented on src/ui/TableOfContent.tsx
> +    console.log('href', href);
stray console logs

2021-10-04 11:53 UTC, kristojorg commented on src/ui/TableOfContent.tsx
> +
Question: 

Is it possible in `usePdfReader` to process the pdf outline into a readium-style `toc`? Then we could just add it to the webpub manifest we return and render it normally using this component

2021-10-04 11:53 UTC, kristojorg commented
Also yea idk what's going on with the linter, it should be using the settings found in the repo, and also should lint fix before committing

2021-10-04 13:43 UTC, hokei commented on package.json
> +    "example": "parcel example/index.html",
Oh right thanks for pointing that out - I am still getting errors when I run locally so I just put it in when developing.

2021-10-06 20:19 UTC, samanthaandrews commented on src/ui/TableOfContent.tsx
> +      console.log('item', item);
stray `console.log()`

2021-10-06 20:28 UTC, samanthaandrews commented
https://user-images.githubusercontent.com/34348332/136277946-1f2e635a-ee9e-4e09-8a5c-d8aed8297128.mov

I'm not sure what the expected behavior is in scroll mode, but I attached a recording of what I noticed when switching from paginated to scrolling mode and then attempting to use the TOC to navigate to a section.

2021-10-06 20:57 UTC, hokei commented
@samanthaandrews oh no that's defs not good.  Thanks for finding it! 
I feel a bit sheepish for never having tested it in scroll mode - but I think the toc doesn't work in scroll mode at all due to the fact that both this TOC functionality, and also scroll mode, are both kind of hacky.  fun.

2021-10-20 17:28 UTC, hokei commented
Closing this PR pending a re-thinking of this work - I will comment this on JIRA ticket so we can refer in the future.

2021-10-20 17:28 UTC, closed without merging